name: infinicat
description: App for images of cats
version: 1.1.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  toast: ^0.1.5
  permission_handler: ^5.0.0+hotfix.4
  settings_ui: ^0.3.0
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.10
  image_save: ^3.0.0
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - assets/
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
